[dependencies]
wasm-bindgen = "^0.2.50"

[package]
name = "wasm"
version = "0.1.0"
authors = [
  "terrierscript <13282103+terrierscript@users.noreply.github.com>"
]
edition = "2018"

[lib]
crate-type = [ "cdylib" ]
